# Generated by Django 5.0.6 on 2024-07-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='invite_reason',
            field=models.TextField(max_length=60),
        ),
    ]
